### ISSUE TITLE
[1.16.3] Client crash on loading - Failure message: ZYCraft (zycraft) encountered an error during the common_setup event phase java.lang.ArrayIndexOutOfBoundsException: 108

### ISSUE THREAD

**Issue by ProsperCraft** [nikita488/ZYCraft#5]
Crash report-
https://gist.github.com/ProsperCraft/ad243a5cd2930fa351f78ce3bbff6709

Log-
https://gist.github.com/ProsperCraft/7c07ebb4d7b6a8667357d03031e60ba9

Version-
ZYCraft-1.16.3-0.1.3.jar

Modpack-
https://www.curseforge.com/minecraft/modpacks/towncraft
TownCraft TWO for 1.16.3 test (ZYCraft isn't added to the pack yet)

**Comment by nikita488** [comment]
Hmm, that's strange. Does it happen always or randomly?

**Comment by ProsperCraft** [comment]
It happened once, has not happened again yet.

**Comment by nikita488** [comment]
That's really strange, but i will keep an eye on it.

**Comment by nikita488** [comment]
Well, it turns out that it's not actually a problem with my mod, but Forge EventBus has some kind of very rare race condition. The Forge team is aware and already tried to fix this, we will see. For now, you can play with my mod as-is, it might crash your pack very rarely and only on modpack loading.

**Comment by nikita488** [comment]
Forge pushed a fix for this problem a long time ago, should not happen anymore.
